#!groovy

node {
    stage('Checkout to HEAD') {
        checkout(scm);

        rc = bat(
            returnStatus: true,
            returnStdout: true,
            script: """\
                git submodule update --init\
            """,
        );
        if (rc != 0) {
            error('Failed to initialize submodules')
        }
    }

    stage('Test Deployment') {
        rc = bat(
            returnStatus: true,
            returnStdout: true,
            script: """\
                submodules\\manifest\\manifest force-app\\main\\default /i\
            """,
        );
        if (rc != 0) {
            error('Manifest generation failed');
        }

        rc = bat(
            returnStatus: true,
            returnStdout: true,
            script: """\
                ant -buildfile ci\\ant\\build.xml\
            """,
        );
        if (rc != 0) {
            error('Test deployment failed');
        }
    }
}
