#!groovy

node {
    stage('Checkout to HEAD') {
        checkout(scm);
    }

    stage('Test Deployment') {
        rc = bat(
            returnStatus: true,
            returnStdout: true,
            script: """\
                ci\\ant\\manifest force-app\\main\\default ${env.SF_API_VERSION} >force-app\\main\\default\\package.xml\
            """,
        );
        if (rc != 0) {
            error('Manifest generation failed');
        }

        rc = bat(
            returnStatus: true,
            returnStdout: true,
            script: """\
                ant -buildfile ci\\ant\\build.xml\
            """,
        );
        if (rc != 0) {
            error('Test deployment failed');
        }
    }
}
