#!groovy

node {
    stage('Checkout to HEAD') {
        checkout(scm);
    }

    withCredentials([file(
        credentialsId: env.SERVER_KEY_CREDENTALS_ID,
        variable: 'JWT_KEY_FILE',
    )]) {
        stage('Authorization') {
            rc = bat(
                returnStatus: true,
                returnStdout: true,
                script: """\
                    sfdx auth:jwt:grant\
                        --clientid ${env.SF_CONSUMER_KEY}\
                        --instanceurl ${env.SF_INSTANCE_URL}\
                        --jwtkeyfile ${JWT_KEY_FILE}\
                        --setdefaultdevhubusername\
                        --username ${env.SF_USERNAME}\
                """,
            );
            if (rc != 0) {
                error('Authorization failed');
            }

            rc = bat(
                returnStatus: true,
                returnStdout: true,
                script: """\
                    sfdx config:set\
                        defaultusername=${env.SF_USERNAME}\
                """,
            );
            if (rc != 0) {
                error('Failed to set default username');
            }
        }
    }

    stage('Test Deployment') {
        rc = bat(
            returnStatus: true,
            returnStdout: true,
            script: """\
                sfdx force:source:deploy\
                    --checkonly\
                    --sourcepath .\
                    --verbose\
                    --testlevel ${env.SF_TEST_LEVEL}\
            """,
        );
        if (rc != 0) {
            error('Test deployment failed');
        }
    }
}
