name: \"Check\" Deploy
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update package index
        run: sudo apt update
      - name: Install Node and NPM
        run: sudo apt install nodejs npm
